language: python
services:
- docker
sudo: required
env:
  global:
    - ENCRYPTION_KEY=ABCGDHEUSHFKIRMJSDFIUTEHFNGOWPOR
    - PATH=$PATH:${HOME}/google-cloud-sdk/bin CLOUDSDK_CORE_DISABLE_PROMPTS=1

install:
  - nvm install 12.14.1
  - npm install
  - pip install -r requirements.txt
  - sudo apt-get install pandoc

before_script:
  - curl -L "https://storage.googleapis.com/google-code-archive-downloads/v2/code.google.com/shunit2/shunit2-2.1.6.tgz" | tar zx

script:
  - bash tests/generate_test.sh
  - python tests/test.py
  - npm run test

after_success:
  - bash kubernetes/travis/deploy.sh
  - bash kubernetes/travis/deploy-staging.sh
