language: python

env:
  global:
    - ENCRYPTION_KEY=ABCGDHEUSHFKIRMJSDFIUTEHFNGOWPOR

install:
  - nvm install 6.0
  - npm install
  - pip install -r requirements.txt

before_script:
  - curl -L "https://storage.googleapis.com/google-code-archive-downloads/v2/code.google.com/shunit2/shunit2-2.1.6.tgz" | tar zx

script:
  - bash tests/generate_test.sh
  - python tests/test.py
  - npm run test

