language: node_js
node_js:
  - "6"

env:
  global:
    - AUTHOR=FOSSASIA
    - DOCPATH=docs/
    - DOCURL=yaydoc.fossasia.org
    - PROJECTNAME=Yaydoc
    - VERSION=development
    - ENCRYPTION_KEY=ABCGDHEUSHFKIRMJSDFIUTEHFNGOWPOR

install:
  - npm install
  - sudo pip install -r requirements.txt

before_script:
  - curl -L "https://storage.googleapis.com/google-code-archive-downloads/v2/code.google.com/shunit2/shunit2-2.1.6.tgz" | tar zx

script:
  - bash tests/generate_test.sh
  - npm run test

before_deploy:
- openssl aes-256-cbc -K $encrypted_cab6203e105e_key -iv $encrypted_cab6203e105e_iv -in .utility/yaydoc_deploy.enc -out .utility/yaydoc_deploy -d
- eval "$(ssh-agent -s)"
- chmod 600 .utility/yaydoc_deploy
- ssh-add .utility/yaydoc_deploy

deploy:
  - provider: script
    skip_cleanup: true
    script: .utility/deploy_docs.sh
    on:
      branch: deploy
  - provider: script
    skip_cleanup: true
    script: .utility/deploy_docs.sh
    on:
      branch: master
