metadata:
  projectname: Yaydoc
  version: development
  author: FOSSASIA

build:
  source: docs/
  theme:
    name: sphinx_fossasia_theme
  github_ribbon:
    color: red

publish:
  ghpages:
    url: yaydoc.fossasia.org
