metadata:
  projectname: Yaydoc
  version: development
  author: FOSSASIA

build:
  source: docs/
  theme: sphinx_fossasia_theme
  github_ribbon:
    color: red

publish:
  ghpages:
    docurl: yaydoc.fossasia.org
